# Generated by Django 3.0.2 on 2020-04-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('held_shares', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numShares', models.IntegerField()),
                ('inv_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='held_shares.InvestedShare')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to='login.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to='login.Profile')),
            ],
        ),
    ]
