# Generated by Django 3.0.2 on 2020-04-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('homeML', models.IntegerField()),
                ('awayML', models.IntegerField()),
                ('homeSpread', models.DecimalField(decimal_places=1, max_digits=10)),
                ('awaySpread', models.DecimalField(decimal_places=1, max_digits=10)),
                ('didHomeWin', models.BooleanField(default=False)),
                ('didHomeSpread', models.BooleanField(default=False)),
                ('didAwayWin', models.BooleanField(default=False)),
                ('didAwaySpread', models.BooleanField(default=False)),
                ('maxToWin', models.DecimalField(decimal_places=2, default=100, max_digits=10000)),
                ('gameStarted', models.BooleanField(default=False)),
                ('gameOver', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seed', models.IntegerField()),
                ('initialAmount', models.IntegerField(default=50)),
                ('americanOdds', models.IntegerField()),
                ('pricePerShare', models.CharField(blank=True, editable=False, max_length=100)),
                ('hidden', models.BooleanField(default=False, editable=False)),
                ('done', models.BooleanField(default=False)),
                ('win', models.BooleanField(default=False)),
            ],
        ),
    ]
