# Generated by Django 3.0.2 on 2020-04-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='initialAmount',
            field=models.IntegerField(default=50),
        ),
    ]
