# Generated by Django 3.0.2 on 2020-04-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
