# Generated by Django 3.0.2 on 2020-04-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20200411_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
