# Generated by Django 3.0.2 on 2020-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20200413_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='awayOdds',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='homeOdds',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='maxToRiskAway',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='maxToRiskHome',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='maxToRiskSpread',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='spreadOdds',
            field=models.FloatField(default=1.91, editable=False),
        ),
    ]
