# Generated by Django 3.0.2 on 2020-04-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20200412_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='hidden',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
