# Generated by Django 3.0.2 on 2020-04-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_auto_20200414_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='maxToWin',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10000, verbose_name='Max Amount to Win'),
        ),
    ]
