# Generated by Django 3.0.2 on 2020-04-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_auto_20200414_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='awayOdds',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='homeOdds',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
