# Generated by Django 3.0.2 on 2020-04-12 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestedShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSharesHeld', models.IntegerField()),
                ('boughtAt', models.CharField(blank=True, max_length=100)),
                ('hidden', models.BooleanField(default=False, editable=False)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.Share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountUsed', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('amOdds', models.IntegerField()),
                ('oddsAtPurchase', models.FloatField()),
                ('bet', models.IntegerField()),
                ('hidden', models.BooleanField(default=False, editable=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shares.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
