# Generated by Django 3.0.2 on 2020-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('held_shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investedgame',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investedshare',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
