# Generated by Django 3.0.2 on 2020-04-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('held_shares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investedshare',
            name='hidden',
        ),
    ]
