# Generated by Django 3.0.2 on 2020-04-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('held_shares', '0002_remove_investedshare_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='investedshare',
            name='hidden',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
