# Generated by Django 3.0.2 on 2020-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('held_shares', '0002_auto_20200413_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investedgame',
            name='amOdds',
            field=models.IntegerField(verbose_name='Odds'),
        ),
        migrations.AlterField(
            model_name='investedgame',
            name='amountUsed',
            field=models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Amount Bet'),
        ),
        migrations.AlterField(
            model_name='investedgame',
            name='bet',
            field=models.IntegerField(verbose_name='Bet Placed'),
        ),
        migrations.AlterField(
            model_name='investedgame',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hide'),
        ),
        migrations.AlterField(
            model_name='investedgame',
            name='oddsAtPurchase',
            field=models.FloatField(verbose_name='Decimal Odds'),
        ),
        migrations.AlterField(
            model_name='investedshare',
            name='boughtAt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Price Purchased'),
        ),
        migrations.AlterField(
            model_name='investedshare',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hide'),
        ),
        migrations.AlterField(
            model_name='investedshare',
            name='numSharesHeld',
            field=models.IntegerField(verbose_name='Number of Shares Held'),
        ),
    ]
