# Generated by Django 3.0.2 on 2020-04-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('held_shares', '0003_investedshare_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investedgame',
            name='hidden',
        ),
    ]
