# Generated by Django 3.0.2 on 2020-04-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('held_shares', '0004_auto_20200415_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investedgame',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investedshare',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
