# Generated by Django 2.2.7 on 2020-04-15 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('held_shares', '0007_auto_20200415_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investedgame',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='investedshare',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
